default_platform(:ios)

platform :ios do
    desc "Run UI tests"
    lane :ui_test do
        run_tests(workspace: "Example/TABTestKit.xcworkspace",
            devices: ["iPhone 11 (16.2)"],
            scheme: "TABTestKit_ExampleUITests")
    end
end