steps:
  - template: git-checkout.yml
  - task: Bash@3
    displayName: "Print environment variable"
    condition: succeededOrFailed()
    inputs:
      targetType: inline
      script: |
        printenv
  - task: Bash@3
    displayName: "Save home directory as a variable"
    condition: succeededOrFailed()
    inputs:
      targetType: inline
      script: |
        echo "##vso[task.setvariable variable=agentHomeDirectory]$HOME"
  - task: Cache@2
    displayName: "Cache Ruby gems written in gemfile.lock file"
    condition: succeededOrFailed()
    continueOnError: true
    inputs:
      key: "$(GEMFILE_LOCK_PATH) | $(DEPENDENCIES_SCRIPT_PATH)"
      path: $(agentHomeDirectory)/.rbenv
  - task: Bash@3
    displayName: "Install dependencies"
    condition: succeededOrFailed()
    inputs:
      targetType: filePath
      filePath: $(DEPENDENCIES_SCRIPT_PATH)
    env:
      RUBY_CONFIGURE_OPTS: "--with-openssl-dir=/usr/local/opt/openssl@1.1"
