steps:
  - template: git-checkout.yml
  - task: Bash@3
    displayName: "Print environment variable"
    condition: succeededOrFailed()
    inputs:
      targetType: inline
      script: |
        printenv
