steps:
  - template: git-checkout.yml
  - task: Bash@3
    displayName: "Print environment variable"
    condition: succeededOrFailed()
    inputs:
      targetType: inline
      script: |
        printenv
  - task: Bash@3
    displayName: "Save home directory as a variable"
    condition: succeededOrFailed()
    inputs:
      targetType: inline
      script: |
        echo "##vso[task.setvariable variable=agentHomeDirectory]$HOME"
  - task: Cache@2
    displayName: "Cache Ruby gems written in gemfile.lock file"
    condition: succeededOrFailed()
    continueOnError: true
    inputs:
      key: "$(GEMFILE_LOCK_PATH) | $(DEPENDENCIES_SCRIPT_PATH)"
      path: $(BUNDLE_PATH)
  - task: Cache@2
    displayName: "Cache Pods"
    condition: succeededOrFailed()
    continueOnError: true
    inputs:
      key: 'pods | $(PODFILE_LOCK_PATH)'
      path: $(POD_DIRECTORY)
  - task: UseRubyVersion@0
    displayName: "Select Ruby version > 2.7.0 to run on an agent"
    inputs:
      versionSpec: "= 2.7"
      addToPath: true
  - task: CocoaPods@0
    displayName: "Install cocoapods and run pod install"
    inputs:
      projectDirectory: $(PODFILE_PATH)
  - task: Bash@3
    displayName: "Install dependencies"
    condition: succeededOrFailed()
    inputs:
      targetType: filePath
      filePath: $(DEPENDENCIES_SCRIPT_PATH)
    env:
      RUBY_CONFIGURE_OPTS: "--with-openssl-dir=/usr/local/opt/openssl@1.1"
