parameters:
  - name: "lane"
    type: string

steps:
  - task: Bash@3
    displayName: "${{ parameters.lane }}"
    condition: succeededOrFailed()
    inputs:
      targetType: inline
      scripts: |
        eval "$(rbenv init -)"
        bundle exec fastlane ${{ parameters.lane }}
