parameters:
  - name: "lane"
    type: string

steps:
  - task: Bash@3
    displayName: "${{ parameters.lane }}"
    condition: succeededOrFailed()
    inputs:
      targetType: inline
      script: |
        eval "$(rbenv init -)"
        bundle exec fastlane ${{ parameters.lane }}
  - task: PublishPipelineArtifact@1
    displayName: "Publish UI test result"
    condition: succeededOrFailed()
    inputs:
      artifactName: $(UI_TEST_RESULT_ARTIFACT_NAME)
      targetPath: $(TEST_OUTPUT_PATH)
