parameters:
  - name: "lane"
    type: string

steps:
  - task: Bash@3
    displayName: "${{ parameters.lane }}"
    condition: succeededOrFailed()
    inputs:
      targetType: inline
      script: |
        eval "$(rbenv init -)"
        echo "Before running bundle exec fastlane"
        bundle exec fastlane ${{ parameters.lane }}
        echo "After running bundle exec fastlane"
