parameters:
  - name: path
    type: string
    default: "/*"

steps:
  - checkout: none
  - task: InstallSSHKey@0
    displayName: "Install SSH key to use with git authentication"
    condition: succeededOrFailed()
    inputs:
      knownHostsEntry: github.com $(github_ssh_public_key_type) $(github_ssh_public_key)
      sshKeySecureFile: azure_pipeline
  - bash: |
      set -x
      cat ~/.ssh/known_hosts
      git clone --filter=blob:none --no-checkout git@github.com:$NATIVE_IOS_REPO_PATH.git $BUILD_SOURCESDIRECTORY
      cd $BUILD_SOURCESDIRECTORY
      git sparse-checkout set "${{ parameters.path }}"
      git fetch --force --tags --prune --prune-tags --progress origin
      git fetch --force --tags --prune --prune-tags --progress origin $GIT_COMMIT_HASH
      git checkout --force --progress $GIT_COMMIT_HASH
    displayName: "Checkout $(NATIVE_IOS_REPO_PATH) ($(GIT_COMMIT_HASH))"
    name: gitCheckout
