# ui-test-shards.yml
parameters:
  - name: envSettings
    displayName: Environment preparation settings
    type: string
  - name: fastlaneSettings
    displayName: Fastlane lane to run
    type: string

jobs:
  - job: build
    displayName: "Run tests"
    steps:
      - template: ${{ parameters.envSettings }}.yml
      - template: fastlane.yml
        parameters:
          lane: "${{ parameters.fastlaneSettings }}"
      - task: PublishPipelineArtifact@1
        displayName: "Publish UI test result"
        condition: succeededOrFailed()
        inputs:
          artifactName: $(UI_TEST_RESULT_ARTIFACT_NAME)
          targetPath: $(TEST_OUTPUT_PATH)
