# ui-test-shards.yml
parameters:
  - name: envSettings
    displayName: Environment preparation settings
    type: string
  - name: fastlaneSettings
    displayName: Fastlane lane to run
    type: string
  - name: jobSettings
    displayName: Pipeline job description
    type: string
  - name: indices
    type: object

jobs:
  - job: build
    displayName: ${{ parameters.jobSettings }}
    steps:
      - template: ${{ parameters.envSettings }}.yml
      - template: fastlane.yml
        parameters:
          lane: "${{ parameters.fastlaneSettings }} build_for_testing:true"
      - task: PublishPipelineArtifact@1
        displayName: "Publish build"
        condition: succeededOrFailed()
        inputs:
          artifactName: $(BUILD_ARTIFACT_NAME)
          targetPath: $(BUILD_OUTPUT_PATH)
  - ${{ each index in parameters.indices }}:
      - job: shard_${{ index }}
        dependsOn: [build]
        condition: succeeded()
        timeoutInMinutes: 15
        steps:
          - template: ${{ parameters.envSettings }}.yml
          - task: DownloadPipelineArtifact@2
            displayName: Download UI test build
            inputs:
              buildType: current
              artifactName: $(BUILD_ARTIFACT_NAME)
              targetPath: $(BUILD_OUTPUT_PATH)
          - template: fastlane.yml
            parameters:
              lane: "ui_test_shard shard_number:${{ index }} --verbose"
          - task: PublishPipelineArtifact@1
            displayName: Publish shard ${{ index }} test results
            condition: succeededOrFailed()
            inputs:
              artifactName: $(UI_TEST_RESULT_ARTIFACT_NAME)${{ index }}
              targetPath: $(TEST_OUTPUT_PATH)
