# ui-test-shards.yml
parameters:
  - name: envSettings
    displayName: Environment preparation settings
    type: string
  - name: fastlaneSettings
    displayName: Fastlane lane to run
    type: string
  - name: jobSettings
    displayName: Pipeline job description
    type: string

jobs:
  - job: build
    displayName: ${{ parameters.jobSettings }}
    steps:
      - template: ${{ parameters.envSettings }}.yml
      - template: fastlane.yml
        parameters:
          lane: "${{ parameters.fastlaneSettings }}"
      - task: PublishPipelineArtifact@1
        displayName: "Publish build"
        condition: succeededOrFailed()
  - job: run tests
    displayName: "Run tests"
    dependsOn: build
    condition: succeededOrFailed()
