# ui-test-shards.yml
jobs:
  - job: build
    steps:
      - template: environment-preparation-without-caching.yml
      - template: fastlane.yml
        parameters:
          lane: "ui_test build_for_testing:true"
      - task: PublishPipelineArtifact@1
        displayName: "Publish UI test result"
        condition: succeededOrFailed()
        inputs:
          artifactName: $(UI_TEST_RESULT_ARTIFACT_NAME)
          targetPath: $(TEST_OUTPUT_PATH)