trigger:
  - main

pool:
  vmImage: "macOS-12"

variables:
  - template: templates/variables.yml

jobs:
  - job: build
    steps:
      - template: templates/environment-preparation-without-caching.yml
      - template: templates/fastlane.yml
        parameters:
          lane: "ui_test build_for_testing:true"
      - task: PublishPipelineArtifact@1
        displayName: "Publish UI test result"
        inputs:
          artifactName: $(UI_TEST_RESULT_ARTIFACT_NAME)
          targetPath: $(TEST_OUTPUT_PATH)
