trigger:
  - test-with-caching

pool:
  vmImage: "macOS-12"

variables:
  - template: templates/variables.yml
  - system.debug: 'true'

stages:
  - stage: ui_tests
    displayName: "UI tests"
    jobs:
      - template: templates/test-configuration.yml
