trigger:
  - main

pool:
  vmImage: "macOS-12"

variables:
  - template: templates/variables.yml

stages:
  - stage: build
    displayName: Build app
    jobs:
      - template: templates/environment-preparation-without-caching.yml

  - stage: test
    displayName: Run UI tests
    dependsOn: [build]
    jobs:
      - template: templates/fastlane.yml
        parameters:
          lane: "ui_test build_for_testing:true"
      steps:
        - task: PublishPipelineArtifact@1
          displayName: "Publish UI test result"
          condition: succeededOrFailed()
          inputs:
            artifactName: $(UI_TEST_RESULT_ARTIFACT_NAME)
            targetPath: $(TEST_OUTPUT_PATH)
