trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - template: templates/variables.yml

jobs:
  - job: build
    steps:
      - template: templates/environment-preparation.yml
      - template: templates/fastlane.yml
        parameters:
          lane: "ui_test build_for_testing:true"
      - task: PublishPipelineArtifact@1
        displayName: "Publish UI test build"
        inputs:
          artifactName: $(UI_TESTT_BUILD_ARTIFACT_NAME)
          targetPath: $(DERIVED_DATA_BUILD_PRODUCTS_PATH)
