trigger:
  - none

pool:
  vmImage: "macOS-12"

variables:
  - template: templates/variables.yml

stages:
  - stage: build_and_run_tests
    displayName: UI tests
    jobs:
      - template: templates/test-configuration.yml
        parameters: 
          envSettings: environment-preparation-without-caching
          fastlaneSettings: build_and_run_ui_test
          jobSettings: Build and Run tests
