trigger:
  - none

pool:
  vmImage: "macOS-12"

variables:
  - template: templates/variables.yml

stages:
  - stage: build_for_testing
    displayName: "Compile the app for testing"
    jobs:
      - template: templates/test-configuration-multiple-agents.yml
        parameters:
          envSettings: environment-preparation-without-caching
          fastlaneSettings: build_for_testing
          jobSettings: 'Build for testing'
